### ISSUE TITLE
Songe-syncer is GREAT! Could it be made to remember where the destination directory is?

### ISSUE THREAD

**Issue by karltinsly** [lolPants/songe-converter#10]
I would like to have songe-syncer remember where the destination folder is, since it rarely changes. It's a wonderful tool and would be even more awesome if I didn't have to tell it where the CustomWIPLevels directory is each time.

**Comment by luludotdev** [comment]
Closed as of 7ab780dc7cfcd4b2c64102010e3299506a056cb2
