### ISSUE TITLE
Convert subdirectories of ID directories

### ISSUE THREAD

**Issue by MCJack123** [lolPants/songe-converter#2]
BeatSaverDownloader downloads levels into ID'd directories and extracts them inside, so this tool should traverse into directories with an ID and one subdirectory if `-a` is passed to allow converting all downloaded levels at once.

**Comment by luludotdev** [comment]
This is intended. You can either use shell commands to walk the directories and pass them as arguments, or use the `--glob` flag to match all `info.json` files.

eg: `./songe-converter --glob **/info.json CustomSongs`
