### ISSUE TITLE
Package layout

### ISSUE THREAD

**Issue by lindell** [lolPants/songe-converter#3]
First, thanks for the tool.

But it would be great if this could be split into a library part and one command part. There are some ways to organize go repos but the most popular is [golang-standards/project-layout](https://github.com/golang-standards/project-layout).

This would mean splitting the project up to one `cmd/songe-converter` with only the main.go file (and flags and logs) and `pkg/songe-converter` for everything else. This would make it much easier to have a well defined library that could be used for more than the command line tool. 

For example, a web server that allows uploads and then conversion of old songs.

**Comment by lindell** [comment]
If this is something that would be interesting to you, I could create a PR for it.

**Comment by luludotdev** [comment]
I personally don't see a huge need for this, as the tool is intended to only really be used once to convert BeatSaver, and then embedded into SongCore to convert libraries locally.

You're welcome to submit a PR anyway, all work is appreciated 😀

**Comment by luludotdev** [comment]
Closed as of 96e8fdf1b3fbb6855eb28e7c739f61bcda670ea4
