### ISSUE TITLE
Converting back to old format?

### ISSUE THREAD

**Issue by StefanH-AT** [lolPants/songe-converter#6]
I looked at the command attributes and can't seem to find an option to port back to the original.
Right now, the editors don't support the new beatmap system so I'm not able to edit any of the maps I converted manually using this tool (I didn't run with -k).

**Comment by Assistant** [comment]
Converting back is impossible in a satisfactory manner.

**Comment by luludotdev** [comment]
This is the entire reason the `--dry-run` and `--keep-original` flags exist. I have no plans to support backwards conversion.
